Table
    - person_body_status
        - id
        - camera_id
        - frame_id
        - body_id
        - body_stat 军人 0: 姿态 1: 写字 2: 其他 -1: unknown 0： 正常姿态 1: 站立 2: 举手 3：睡觉 4：手托头听课 5：趴着听课
        - body_track
        - face_id 学生学号 通过人脸识别之后定位到学生的基本信息
        - face_track
        - face_pose  -1: unknown 0： 平视 1: 左顾右盼 2: 低头
        - face_pose_stat 0： 表示正常 1: 表示不正常
        - face_pose_stat_time
        - face_emotion -1: unknown 0: 正常 1: 开心 2: 低落
        - yawn 0: 没有 1: 打哈欠
        - unix_timestamp
        - pose_stat_time: max(body_stat\face_ose) group by pose_stat_time
        - course_name: 学科

        精神状态 （课堂）
            - 疲惫
                body_stat
                    - body_stat 4， 5 次数 >= 10
                emotion
                    - 开心 <= 3 or 低落 >= 10
            - 积极
                body_stat
                    - 1 >= 2 or 2 >= 2
                emotion
                    - 微笑 >= 10
            - 正常
                else

        学习状态 （课堂）
            - 不佳
                精神状态
                    - 疲惫
                face_pose
                    - 按课堂检测到 (正常 face_pose_stat = 0) 平视的次数降序 最后 10% === <= 90%
            - 非常好
                精神状态
                    - 积极
                face_pose
                    - 按课堂检测到 (正常 face_pose_stat = 0) 平视的次数降序 Top 10%
            - 良好
                精神状态
                    - 积极 或者 正常
                face_pose
                    - 按课堂检测到 (正常 face_pose_stat = 0) 平视的次数降序 Top 40%
            - 正常
                else

        情绪 （天） 阈值 + Top K
            - 低落
                emotion
                    - 低落次数 >= 50 && 低落次数降序 Top 10%
            - 开心
                emotion
                    - 开心次数 >= 50 && 开心次数降序 Top 30%
            - 正常 - other

        人际关系 (课间数据) 数据累计>= 30 && 该学生出现次数 >= 500 才会评估
            - 孤僻
                face_pose
                    - 低头 比例 >= 60%
                emotion
                    - 微笑 比例 <= 1%
            - 非常好
                face_pose
                    - 左顾右盼 比例 >= 30%
                emotion
                    - 微笑 比例 >= 10%
            - 良好
                face_pose
                    - 左顾右盼 比例 >= 15%
                emotion
                    - 微笑 比例 >= 5%
            - 正常 - other

        学科兴趣 (课堂) 数据积累 >= 30
            科目
                - 学习状态 （天）
                    良好 + 非常好 >= 60%
                - 成绩
                    >= 80分 [0-150] => [0-100]）
                - or 个人证书

Output Table
    - student_mental_status_ld
        - student_number
        - student_name
        - class_id
        - grade_name
        - class_name
        - student_relationship
        - student_emotion
        - student_mental_stat
        - student_study_stat
        - student_interest
        - dt

    - student_mental_status_course_daily
        - student_number
        - student_name
        - class_id
        - grade_name
        - class_name
        - course_name
        - student_mental_stat
        - student_study_stat
        - dt

    - student_mental_status_interest_daily
        - student_number
        - student_name
        - class_id
        - grade_name
        - class_name
        - student_interest
        - dt

    - student_mental_status_grade_study_daily
        - student_number
        - course_name
        - grade_level
        - study_level
        - dt

Middle Table
    - person_body_status_face_track
        - camera_id
        - frame_id
        - body_id
        - body_stat 军人 0: 姿态 1: 写字 2: 其他 -1: unknown 0： 正常姿态 1: 站立 2: 举手 3：睡觉 4：手托头听课 5：趴着听课
        - body_track
        - face_id 学生学号 通过人脸识别之后定位到学生的基本信息
        - face_track
        - face_pose  -1: unknown 0： 平视 1: 左顾右盼 2: 低头
        - face_pose_stat 0： 表示正常 1: 表示不正常
        - face_pose_stat_time
        - face_emotion -1: unknown 0: 正常 1: 开心 2: 低落
        - yawn 0: 没有 1: 打哈欠
        - unix_timestamp
        - pose_stat_time: max(body_stat\face_ose) group by pose_stat_time

    - person_body_status_pose_stat_midlle
        - camera_id
        - face_id
        - pose_stat_time
        - face_pose_stat_time
        - body_stat
        - face_pose
        - face_emotion

    - person_body_status_face_pose_stat
        - camera_id
        - face_id
        - pose_stat_time
        - body_stat
        - face_pose
        - face_emotion
        - face_pose_stat

    - person_body_status_course_info
        - camera_id
        - class_id
        - face_id
        - pose_stat_time
        - body_stat
        - face_pose
        - face_emotion
        - face_pose_stat
        - course_name

School Class Info
    # dt 表示时间
    # 班级学生对照表
    - school_student_class_info
        - grade_name 年级
        - class_name 班级
        - student_number 学号
        - student_name 学生姓名
        - dt

    # 摄像头班级对照表
    - school_camera_class_info
        - camera_id 摄像头ID
        - camera_addr 摄像头网络地址
        - class_id 班级唯一ID 跨年级的ID
        - class_name 班级
        - grade_name 年级
        - dt

    # 课程表
    - school_course_info
        - id 自增主键
        - course_id 课程ID
        - course_name 课程名称
        - tea_id 任课
        - tea_name 任课老师
        - class_name 班级名称
        - grade_name 年级名称
        - start_time 开始时间
        - end_time 结束时间
        - dt 天维度的日期，例如: 20181012

    # 成绩表
    - school_performance_info
        - student_number 学号
        - student_name 姓名
        - grade_name 年级
        - class_name 班级
        - course_id 课程ID
        - course_name 课程名称
        - score 成绩考分
        - dt

    # 学生获奖信息表
    - school_award_info
        - student_number 学号
        - student_name 姓名
        - award_type 获奖类别
        - award_level 获奖等级
        - award_name 获奖名称
        - dt

问题:
    - dt字段是否需要修改为long or int型 sTry类型的在比较的时候是按照字符的顺序比较，容易出错 2 100 (100 < 2)